### ISSUE TITLE
Still unable to download!

### ISSUE THREAD

**Issue by kamakshidasan** [Hrily/TopMusicPull#21]
```
$ music_crawler "Top Tracks of Adele" "Music" 1
```

Getting playlist...
Playlist Title : Top Tracks of Adele
Top videos :
	      Adele - Rolling in the Deep
	      Adele - Someone Like You
	      Adele - Set Fire To The Rain (Live at The Royal Albert Hall)
Download? (Y/n) y
Fetching : Rolling in the Deep - Adele
WARNING: unable to set language: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
ERROR: Unable to download webpage: <urlopen error [Errno 8] _ssl.c:510: EOF occurred in violation of protocol>
youtube-dl : [Error]
Playlist updated

**Comment by Hrily** [comment]
@kamakshidasan 
The error seems to be in youtube-dl. 
Can you try updating youtube-dl and try again?

**Comment by sbshah97** [comment]
@kamakshidasan 
Kindly check out this link [here](http://askubuntu.com/questions/380438/how-can-i-update-youtube-dl).
Also let us know if it works out for you! If it does, kindly close the Issue!
Thank you! :smile:

**Comment by sbshah97** [comment]
@kamakshidasan Is this Issue resolved?

**Comment by kamakshidasan** [comment]
Yes - it is! I am closing this. :)
